// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VetWebMVC.Context;

#nullable disable

namespace VetWebMVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VetWeb.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnimalId"));

                    b.Property<string>("Comorbidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condicao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaseDaVida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParametrosId")
                        .HasColumnType("int");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnimalId");

                    b.HasIndex("ParametrosId");

                    b.ToTable("Animais");
                });

            modelBuilder.Entity("VetWeb.EfeitoSistemico", b =>
                {
                    b.Property<int>("EfeitoSistemicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EfeitoSistemicoId"));

                    b.Property<bool>("PodeAumentarFrequenciaCardiaca")
                        .HasColumnType("bit");

                    b.Property<bool>("PodeAumentarFrequenciaRespiratoria")
                        .HasColumnType("bit");

                    b.Property<bool>("PodeAumentarHematocritos")
                        .HasColumnType("bit");

                    b.Property<bool>("PodeAumentarLeucocitos")
                        .HasColumnType("bit");

                    b.Property<bool>("PodeAumentarPressaoArterial")
                        .HasColumnType("bit");

                    b.Property<bool>("PodeDiminuirFrequenciaCardiaca")
                        .HasColumnType("bit");

                    b.Property<bool>("PodeDiminuirFrequenciaRespiratoria")
                        .HasColumnType("bit");

                    b.Property<bool>("PodeDiminuirHematocritos")
                        .HasColumnType("bit");

                    b.Property<bool>("PodeDiminuirLeucocitos")
                        .HasColumnType("bit");

                    b.Property<bool>("PodeDiminuirPressaoArterial")
                        .HasColumnType("bit");

                    b.HasKey("EfeitoSistemicoId");

                    b.ToTable("EfeitoSistemico");
                });

            modelBuilder.Entity("VetWeb.Parametros", b =>
                {
                    b.Property<int>("ParametrosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParametrosId"));

                    b.Property<string>("FrequenciaCardiaca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrequenciaRespiratoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hematocrito")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Leucocitos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PressaoArterialSistemica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ParametrosId");

                    b.ToTable("Parametros");
                });

            modelBuilder.Entity("VetWeb.Remedio", b =>
                {
                    b.Property<int>("RemedioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RemedioId"));

                    b.Property<string>("EfeitoAdverso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EfeitoSistemicoId")
                        .HasColumnType("int");

                    b.Property<string>("MecanismoAcao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrincipioAtivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViaAdministracao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RemedioId");

                    b.HasIndex("EfeitoSistemicoId");

                    b.ToTable("Remedios");
                });

            modelBuilder.Entity("VetWeb.Animal", b =>
                {
                    b.HasOne("VetWeb.Parametros", "Parametros")
                        .WithMany()
                        .HasForeignKey("ParametrosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parametros");
                });

            modelBuilder.Entity("VetWeb.Remedio", b =>
                {
                    b.HasOne("VetWeb.EfeitoSistemico", "EfeitoSistemico")
                        .WithMany()
                        .HasForeignKey("EfeitoSistemicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EfeitoSistemico");
                });
#pragma warning restore 612, 618
        }
    }
}
